mode:
  debug: true

log:
  level: 0

server:
  addr: "0.0.0.0:8090"
  cert: ""
  key: ""

db:
  driverName: "sqlite"
  dataSourceName: "db.sqlite"

sms:
  url: ""
  apiKey: ""
  templateId: ""

observability:
  pprof:
    enabled: true
  prometheus:
    enabled: true
  jaeger:
    enabled: true
