definitions:
  api.ReqLogin:
    properties:
      back_url:
        type: string
      phone:
        type: string
    required:
    - phone
    type: object
  api.Resp:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
    type: object
info:
  contact: {}
  title: Swagger Doc
  version: "1.0"
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login credentials
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/api.ReqLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Resp'
      summary: User otp login
      tags:
      - authentication
swagger: "2.0"
